### PR TITLE
Stabilize filefield_paths

### PR DESCRIPTION
**Pull request by sherakama**
# READY FOR REVIEW

See testing steps in: https://github.com/SU-SWS/acsf-cardinald7/pull/191

### CODE REVIEW

**Comment by sherakama** [comment]
Ready for review.

**Comment by sherakama** [comment]
@minorwm @jbickar someone? Bueller?

**Comment by jbickar** [comment]
Ah, this is ringing a bell. Those linked testing steps do not tell the full story. Basically:

1. check out this branch
2. `composer update drupal/filefield_paths`
3. Ensure that you have 7.x-1.1
4. Deploy to an environment that has the `diseval` library.
5. Ensure that `filefield_paths` works and does not cause PHP fatal errors with `diseval`.

**Comment by sherakama** [comment]
ping

**Comment by sherakama** [comment]
I'm giving up on this.

**Pull request closed without merging**
