### PR TITLE
Fix private page menu install

### PR DESCRIPTION
**Pull request by sherakama**
The parent reference is the key of the $items[] array. 
See line 232 for how the loop gets the parent mlid.

### CODE REVIEW

**Comment by sherakama** [comment]
@boznik,

I just looked at the menu hierarchy and it does not look like you want a parent at all for these items. in that case I would remove the parent key reference for the private pages menu items.

**Comment by boznik** [comment]
@sherakama 
are you saying to unset the parent and assign $v['plid'] to an empty array?

**Comment by sherakama** [comment]
Yeah, 

Looking at: https://sites.stanford.edu/jse-dev/private/for-faculty

It looks like the only entry in the $item array that should have a parent index should be the faculty sub page. All of the other items are at the top of the menu.

**Comment by sherakama** [comment]
The reason it is working is because there is no $item['parent']...

**Pull request closed without merging**
