### PR TITLE
SITES-778: Upgrade path for help pages.

### PR DESCRIPTION
**Pull request by sherakama**
# READY

See: https://github.com/SU-SWS/stanford_sites_jumpstart_academic/pull/30

### CODE REVIEW

**Comment by sherakama** [comment]
ping

**Comment by sherakama** [comment]
@jbickar @boznik ping

**Comment by jbickar** [comment]
Do you only ping at 4:30 on Fridays?

**Comment by jbickar** [comment]
@sherakama do you have a site to test this with?

**Comment by sherakama** [comment]
This got left behind in this series: https://github.com/SU-SWS/stanford_sites_jumpstart_academic/pull/30

@boznik What would an older site be that would have an outdated help page? 

The other option would be to install an old version of this profile and then check out this branch and run the updates.

**Comment by jbickar** [comment]
I'm having trouble getting local copies of JSE sites up and running. Still looking at this.

**Comment by jbickar** [comment]
This works for me. I downloaded a copy of `jse-mskc` into the `cardinald7` codebase, checked out this version, and the help page content re-appeared at `admin/stanford-jumpstart`.

**Review by jbickar — APPROVED** [review]

**Comment by sherakama** [comment]
Woot!

**Pull request merged**
