### PR TITLE
Basic 1779

### PR DESCRIPTION
**Pull request by sherakama**
This PR is dependant on the stanford_tasks PR for the help work but also fixes the missing 404 setting in JSE.

### CODE REVIEW

**Comment by sherakama** [comment]
Fixed up some stuff.

**Comment by sherakama** [comment]
@cjwest,

This PR will fix the help section and the missing 404 page setting in JSE.

**Comment by tsui1** [comment]
:clap:

**Comment by tsui1** [comment]
@sherakama I take it this PR also address : https://stanfordits.atlassian.net/browse/SOE-691 ?

**Comment by sherakama** [comment]
Yes, 
There is about a dozen or so tickets in BASIC and other projects that are related to this work. I am going to have to find some time to do some grooming.

**Pull request merged**
