### PR TITLE
SOE-1695: Enable gallery_block and gallery_administration

### PR DESCRIPTION
**Pull request by cjwest**
# READY FOR REVIEW!!

# Summary
Would you look at that? We never enabled these modules in JSE!

# Needed By (Date)
- Thursday, 3/16

# Urgency
- Not urgent

# Steps to Test

1. Build JSE production 
2. Run behat tests:` $../../bin/behat -p your-jse-prod -s dev features/stanford_gallery`
3. Verify they pass!

# Affected Projects or Products
- JSE Product

# Associated Issues and/or People
- https://stanfordits.atlassian.net/browse/SOE-1695
- Other PRs: https://github.com/SU-SWS/stanford-jumpstart-deployer/pull/133, and https://github.com/SU-SWS/linky_clicky/pull/149

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by cjwest** [comment]
@boznik,
This successfully enables the modules.

Test with:
../../bin/behat -p your-site-profile -s dev features/stanford_gallery

**Comment by boznik** [comment]
--- Failed scenarios:

    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_gallery/stanford_gallery.feature:7
    /Users/ggarvey/www/linky_clicky/includes/features/SU-SWS/stanford_gallery/stanford_gallery_block.feature:7

2 scenarios (2 failed)
160 steps (52 passed, 2 failed, 106 skipped)
1m49.84s (17.72Mb)

**Comment by cjwest** [comment]
@boznik, any more info on what failed? 
Line 7 is: 
Scenario: Create stanford gallery node

That should pass even without this PR.

Verify you're on this version of linky-clicky:
https://github.com/SU-SWS/linky_clicky/pull/149/files

What command and what directory are you using to run linky-clicky?

**Comment by tsui1** [comment]
🎬

**Pull request merged**
